### ISSUE TITLE
不明觉厉

### ISSUE THREAD

**Issue by AoEiuV020** [aping-foo/bcp#1]
tcp不是有丢包重传的吗？
就算弱网，
要么接收不到，要么接收正确，

**Comment by aping-fo** [comment]
哈哈，其实想的是弱网下容易闪断，在这种情况下，你并不能保证一定能收到完整的数据
一个数据发送出去，在TCP底层可能已经拆成N个片段，并对每个片段检测是否要重传
TCP重传也只能保证在网络连通的情况下保证不丢包，
针对业务层面的完整数据包，TCP是无法保证的吧。
闪断后TCP重连过来后，还能继续收到断开之前的回应包

举个通俗易懂的例子，客户端向服务器请求一个文件(大小可能很大，可能很小)，这个传输过程你是无法保证文件能完整的传输完，如果客户端闪断了，整个传输就中断了。

小弟知识浅薄，多多指教 ^_^

**Comment by AoEiuV020** [comment]
听起来像是在协议层面实现断点续传的感觉，
貌似有可行性，
加油，star了等你写完再来看看，
